Itransition/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import include, url
from django.contrib import admin
from Users import views

urlpatterns = (
    url(r'^$', 'Users.views.home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^accounts/profile', 'Users.views.home', name='home'),
    url(r'^new/', views.UploadView.as_view(), name='new'),
    url(r'^open/(?P<pk>[a-z]{6})/$', views.ImageView.as_view(), name='detail'),
    url(r'^change_theme/$', 'Users.views.change_theme', name='change_theme'),
    url(r'^$/change/', 'Users.views.home', name='change'),
    url(r'^edit/(?P<pk>[a-z]{6})/$', views.ChangeView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>[a-z]{6})/$', views.RemoveView.as_view(), name='delete'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^comments/like/(?P<slug>.*)/(?P<x>[0-9]+)/$', views.vote_image, name='like'),
    url(r'^comments/like/(?P<slug>.*)/$', views.vote_image, name='like'),
    url(r'^comments/vote/(?P<id>.*)/$', views.like_comment, name='vote'),
    url(r'^comments/delete_own/(?P<id>.*)/$', views.delete_comment, name='delete_comment'),
    url(r'^user/(?P<id>.*)/$', views.user_page, name='user'),
    url(r'^tag/(?P<tag>.*)/$', views.find_by_tag, name='tag'),
    url(r'^search/$', views.find, name='search'),
)

Users/models.py
import string
import random
from django.db import models
from pyuploadcare.dj import ImageField
import pyuploadcare.api_resources as UploadAPI
from django.contrib.auth.models import User
import PIL.Image as PImage
from PIL import ImageDraw2
import urllib.request
import io
import os
from django_comments.models import Comment
import secretballot
import Itransition.settings as settings

def create_text(draw, image, inner_size, is_top):
    if is_top:
        text = image.top_text
        add = 0
    else:
        text = image.bottom_text
        add = inner_size + 150
    size = 64
    font = ImageDraw2.Font('white', os.path.join('C:\Windows\Fonts', 'arial.ttf'), size)
    while draw.textsize(text, font)[0] > 500:
        font = ImageDraw2.Font('white', os.path.join('C:\Windows\Fonts', 'arial.ttf'), size)
        size -= 1
    size = draw.textsize(text, font)
    draw.text((300 - size[0]/2, add + 75 - size[1]/2), text, font)

def get_full_path(path):
    return settings.BASE_DIR + "\\" + os.path.relpath(path)

def create_demotivator(image):
    url = str(image.image)
    url += '-/stretch/off/-/resize/500x/'
    path = settings.BASE_DIR + "\\" + os.path.relpath('Users/static/images/demotivators/' + str(image.slug) + '-source.jpg')
    urllib.request.urlretrieve(url, path)
    path = io.BytesIO(urllib.request.urlopen(url).read())
    im = PImage.open(path)
    if im.size[0] < 500:
        im = im.resize((500, int(im.size[1] * (500 / im.size[0]))))
    height = im.size[1] + 300
    dem = PImage.new('RGB', (600, height))
    draw = ImageDraw2.Draw(dem)

    create_text(draw, image, im.size[1], True)
    create_text(draw, image, im.size[1], False)

    draw.rectangle((40, 140, 560, im.size[1] + 160), 'white')
    dem.paste(im, (50, 150))
    path = settings.BASE_DIR + "\\" + os.path.relpath('Users/static/images/demotivators/' + str(image.slug) + '.jpg')
    dem.save(path, 'jpeg')
    new = UploadAPI.File.upload(open(get_full_path('Users/static/images/demotivators/' + str(image.slug) + '.jpg'), 'rb'))
    new.store()
    urllib.request.urlretrieve(str(new) + '-/preview/1000x200/-/quality/best/', get_full_path('Users/static/images/demotivators/' + str(image.slug) + '-mini.jpg'))
    return new


class Image(models.Model):
    top_text = models.CharField(max_length=50)
    bottom_text = models.CharField(max_length=50)
    author = models.CharField(max_length=50, null=True)
    slug = models.SlugField(max_length=10, primary_key=True, blank=True)
    image = ImageField(manual_crop="")
    result = ImageField(null=True, blank=True)
    tags = models.CharField(max_length=50, null=True, blank=True)

    def __repr__(self):
        return u'<Image slug={0} image={1}>'.format(self.slug, self.image)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = ''.join(random.sample(string.ascii_lowercase, 6))
        if not self.result:
            self.result = create_demotivator(self)

        ImageTags.objects.filter(image=self).delete()
        for tag in self.tags.split():
            new_tag = Tags.objects.get_or_create(tag=tag)[0]
            ImageTags.objects.create(image=self, tag=new_tag)

        super(Image, self).save(*args, **kwargs)

    def get_likes(self):
        slug = self.slug
        image_vote = ImageVote.objects.filter(image_slug=slug)
        total = 0
        if image_vote:
            if image_vote[0].vote_value:
                for x in range(len(image_vote)):
                    total += image_vote[x].vote_value
                if len(image_vote) != 0:
                    total /= len(image_vote)
        return total

    def normal_url(self):
        return 'images/demotivators/' + self.slug + '.jpg'

    def source_url(self):
        return 'images/demotivators/' + self.slug + '-source.jpg'

    def mini_url(self):
        return 'images/demotivators/' + self.slug + '-mini.jpg'

    @models.permalink
    def get_absolute_url(self):
        return 'detail', (), {'pk': self.pk}


class ImageVote(models.Model):
    id = models.AutoField(primary_key=True)
    image_slug = models.SlugField(max_length=10)
    user_id = models.IntegerField()
    vote_value = models.IntegerField(null=True)


class Tags(models.Model):
    id = models.AutoField(primary_key=True)
    tag = models.CharField(max_length=30)


class ImageTags(models.Model):
    image = models.ForeignKey('Image')
    tag = models.ForeignKey('Tags')

secretballot.enable_voting_on(Comment)

Users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Image, ImageVote, Tags, ImageTags
from django.contrib.auth.decorators import login_required
from django.http import Http404
import pyuploadcare.api_resources as upload_api
from pyuploadcare import InvalidRequestError
from django_comments.models import Comment
from django import http
from secretballot.models import Vote
from django.db.models import Q
from django.contrib.auth.models import User
import os.path
import time
import Itransition.settings as settings


def find(request):
    string = request.POST.get('string')
    backup = string if string else ""
    string = string.lower() if string else ""
    users = []
    images = []
    for user in User.objects.all():
        if user.username.lower().find(string) != -1 or user.first_name.lower().find(string) != -1 or user.last_name.lower().find(string) != -1:
            users.append(user)
    for image in Image.objects.all():
        if image.top_text.lower().find(string) != -1 or image.bottom_text.lower().find(string) != -1 or image.tags.lower().find(string) != -1:
            images.append(image)
    context = {'string': backup, 'users': users, 'images': images}
    return render(request, 'search.html', context)


def find_by_tag(request, tag):
    tag = Tags.objects.filter(tag=tag).first()
    image_tags = ImageTags.objects.filter(tag=tag)
    amount = len(image_tags)
    context = {'image_tags': image_tags[::-1], 'tag': tag, 'amount': amount}
    return render(request, "tag.html", context)


def user_page(request, id):
    user = get_object_or_404(User, id=id)
    images = Image.objects.filter(author=user.username)
    name = " ".join([user.first_name, user.last_name])
    comments = Comment.objects.filter(Q(user_name=name) | Q(user_name=user.username))
    total_likes = 0
    total_vote = 0
    for x in range(len(comments)):
        total_likes += comments[x].total_upvotes
    count = 0
    for x in range(len(images)):
        add = Image.get_likes(images[x])
        total_vote += add
        if add != 0:
            count += 1
    if count != 0:
        total_vote /= count
    context = {'images': images, 'username': user.username, "likes": total_likes,
               'vote': total_vote.__round__(2), 'amount': len(images)}
    return render(request, "user.html", context)


@login_required()
def like_comment(request, id):
    comment = get_object_or_404(Comment, id=id)
    try:
        if Vote.objects.get(object_id=id, token=request.user.id):
            comment.remove_vote(request.user.id)
    except Vote.DoesNotExist:
        comment.add_vote(request.user.id, 1)
    return http.HttpResponseRedirect(comment.content_object.get_absolute_url())


def delete_comment(request, id):
    comment = get_object_or_404(Comment, id=id)
    if comment.user.id != request.user.id and not request.user.is_staff:
        raise Http404
    comment.delete()
    return http.HttpResponseRedirect(comment.content_object.get_absolute_url())


@login_required()
def vote_image(request, slug, x):
    vote = ImageVote.objects.get_or_create(user_id=request.user.id, image_slug=slug)
    vote[0].vote_value = int(x)
    vote[0].save()
    return http.HttpResponseRedirect('/open/' + slug + '/')


class UploadView(CreateView):
    model = Image
    fields = ('slug', 'image', 'result', 'top_text', 'bottom_text', 'author', 'tags')


class ChangeView(UpdateView):
    model = Image
    fields = ('image', 'result', 'top_text', 'bottom_text', 'author', 'tags')

    def get_object(self):
        obj = super(UpdateView, self).get_object()
        obj.result = None

        if self.request.user.username != obj.author and not self.request.user.is_staff:
            raise PermissionError()

        try:
            if obj.image.is_removed():
                raise ValueError('File was deleted.')
        except (InvalidRequestError, ValueError):
            new_image = upload_api.File.upload(open('Users/static/' + obj.normal_url(), 'rb'))
            new_image.store()
            obj.result = new_image
            new_source = upload_api.File.upload(open('Users/static/' + obj.source_url(), 'rb'))
            new_source.store()
            obj.image = new_source
            obj.save()
        return obj


class RemoveView(DeleteView):
    model = Image
    success_url = '/'

    def get_object(self):
        obj = super(DeleteView, self).get_object()
        if self.request.user.username != obj.author and not self.request.user.is_staff:
            raise PermissionError()
        return obj

    def post(self, request, *args, **kwargs):
        obj = super(DeleteView, self).get_object()
        os.remove(settings.BASE_DIR + "\\" + os.path.relpath('Users/static/' + obj.normal_url()))
        os.remove(settings.BASE_DIR + "\\" + os.path.relpath('Users/static/' + obj.source_url()))
        os.remove(settings.BASE_DIR + "\\" + os.path.relpath('Users/static/' + obj.mini_url()))
        ImageTags.objects.filter(image_id=obj.slug).delete()
        ImageVote.objects.filter(image_slug=obj.slug).delete()
        Comment.objects.filter(object_pk=obj.slug).delete()
        return DeleteView.post(self, request, args, kwargs)


class ImageView(DetailView):
    model = Image

    def get_object(self):
        obj = super(ImageView, self).get_object()
        obj.tags = ImageTags.objects.filter(image=obj)
        return obj

    def get_context_data(self, **kwargs):
        context = super(ImageView, self).get_context_data(**kwargs)
        obj = super(ImageView, self).get_object()
        context['author_id'] = User.objects.filter(username=obj.author).first().id if len(User.objects.all()) else 0
        context['stars'] = self.model.get_likes(obj).__round__(2)
        round_likes = int(self.model.get_likes(obj))
        context['filled_star_amount'] = round_likes
        context['star_amount'] = range(5)
        context['userId'] = self.request.user.id
        image_votes = ImageVote.objects.all().filter(image_slug=obj.slug, user_id=self.request.user.id)

        comments = Comment.objects.filter(object_pk=obj.slug, is_removed=False)
        user_likes = []
        for i in range(len(comments)):
            user_likes.append(True)
            try:
                im = Vote.objects.get(token=self.request.user.id, object_id=comments[i].id)
            except Vote.DoesNotExist:
                user_likes.pop()
                user_likes.append(False)
        data = zip(comments, user_likes)
        context['data'] = data
        context['can_vote'] = (len(image_votes) == 0)
        path = settings.BASE_DIR + "\\" + os.path.relpath('Users/static/' + obj.normal_url())
        context['date'] = time.strftime("%d.%m.%y, %H:%M:%S", time.gmtime(os.path.getmtime(path)))
        return context


def home(request):
    def get_tag_cloud():
        _cloud = {}
        for tag in Tags.objects.all():
            _cloud[tag.tag] = len(ImageTags.objects.filter(tag=tag))
        _cloud = list(_cloud.items())
        _cloud.sort(key=lambda item: item[1], reverse=True)
        return _cloud[:10]

    if 'theme' not in request.session:
        request.session['theme'] = 'default'
        request.session.modified = True

    images = Image.objects.all()[::-1]
    cloud = get_tag_cloud()
    context = {'images': images, 'cloud': cloud}
    return render(request, "profile.html", context)


@login_required()
def change_theme(request):
    if request.session['theme'] == 'dark':
        request.session['theme'] = 'default'
        request.session.modified = True
    else:
        request.session['theme'] = 'dark'
        request.session.modified = True
    return redirect(request.POST.get('next'))

templates/Users/image_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить данный демотиватор?</p>
        <input class="btn btn-primary" type="submit" value="Удалить" />
    </form>

{% endblock %}

templates/Users/image_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    {% load comments %}
    <h2><a href="/user/{{ author_id }}/">{{ image.author }}</a> ({{ date }})</h2>

    <a href="{% static image.normal_url %}" target="_blank">
        <img align="left" width="500px" src="{% static image.normal_url %}"></a>

        <p><a href="{% static image.normal_url %}" target="_blank"><img src="{% static "images/link.png" %}" width="50px" style="padding-left: 10px;"/></a></p>
        {% if image.author == user.username or user.is_staff%}
        <p><a href="/edit/{{ image.slug }}"><img src="{% static "images/edit.png" %}" width="50px" style="padding-left: 10px;"/></a></p>
        <p><a href="/delete/{{ image.slug }}"><img src="{% static "images/delete.png" %}" width="50px" style="padding-left: 10px;"/></a></p>
        {% endif %}

    <br clear="left">

    <div style="font-size: 35px; padding-top: 10px;">
    {% for x in star_amount %}
        {% if forloop.counter <= filled_star_amount %}
            {% if can_vote %}
                <a href="{% url 'like' image.slug forloop.counter %}" class="glyphicon glyphicon-star" style="color: lightskyblue;"></a>
            {% else %}
                <a href="{% url 'like' image.slug forloop.counter %}" class="glyphicon glyphicon-star" style="color: #337AB7;"></a>
            {% endif %}
        {% else %}
            {% if can_vote %}
                <a href="{% url 'like' image.slug forloop.counter %}" class="glyphicon glyphicon-star-empty" style="color: lightskyblue;"></a>
            {% else %}
                <!--<text class="glyphicon glyphicon-star-empty"></text>-->
                <a href="{% url 'like' image.slug forloop.counter %}" class="glyphicon glyphicon-star-empty" style="color: #337ab7;"></a>
            {% endif %}
        {% endif %}
    {% endfor %}
    <b>{{ stars }}</b>
    </div>

    {% for tag in image.tags %}
    <a href="/tag/{{ tag.tag.tag }}/"><text class="btn btn-info"><text class="glyphicon glyphicon-tag"></text> {{ tag.tag.tag }}</text></a>
    {% endfor %}

    <div id='comments'>
        {% get_comment_list for object as comment_list %}
            <hr>
            {% for comment, user_like in data %}
                <div>
                    <p style="font-size: smaller; color: darkgray"><a href="/user/{{ comment.user_id }}/"><text class="glyphicon glyphicon-user"></text> {{ comment.user_name }}</a> ({{ comment.submit_date }})
                    {% if comment.user == user or user.is_staff %}
                        <a href="{% url 'delete_comment' comment.id %}" class="glyphicon glyphicon-remove align-right"></a>
                    </p>
                </div>
                    {% endif %}
                <p>{{ comment.comment }}
                {% if userId == comment.user.id %}
                     <text class="glyphicon glyphicon-heart" style="color: lightgray"></text>
                {% elif user_like %}
                    <a href="{% url 'vote' comment.id %}" class="glyphicon glyphicon-heart" style="color: #337ab7"></a>
                {% else %}
                    <a href="{% url 'vote' comment.id %}" class="glyphicon glyphicon-heart-empty" style="color: lightskyblue"></a>
                {% endif %}
                    {{ comment.total_upvotes }}
                </p>
                <div id="{{ comment.id }}"></div>
                <hr>
            {% endfor %}

        {% if user.is_authenticated %}
            {% get_comment_form for object as form %}
            <form action="{% comment_form_target %}" method="POST">
            {% csrf_token %}
            <textarea id="id_comment" name="comment" maxlength="3000" rows="4" style="width: 500px"></textarea>
            {{ form.content_type }}
            {{ form.object_pk }}
            {{ form.timestamp }}
            {{ form.security_hash }}
            <input type="hidden" id="id_next" name="next" value="{{ object.get_absolute_url }}">
            <br>
            <input class="btn btn-primary" type="submit" value="Отправить" id="id_submit"/>
            </form>
        {% else %}
        {% endif %}
    </div>
    <br>
{% endblock %}

templates/Users/image_form.html
{% extends "base.html" %}


{% block head %}
	<script>
	UPLOADCARE_TABS = 'all';
	UPLOADCARE_PUBLIC_KEY = 'demopublickey';
	</script>
	{{ form.media }}
{% endblock %}


{% block content %}
	<div>
		<form action="." method="post" id="upload-form" class="center">
            {% csrf_token %}
            <input id="id_author" name="author" type="hidden" value="{{ user.username }}">
            <table>
                <tr>
                    <td width="100"><p>Верхний текст:</p></td>
                    <td><input id="id_top_text" name="top_text" type="text" style="width: 300px;" value="{{ image.top_text }}"></td>
                </tr>
                <tr>
                    <td><p>Нижний текст:</p></td>
                    <td><input id="id_bottom_text" name="bottom_text" type="text" style="width: 300px;" value="{{ image.bottom_text }}"></td>
                </tr>
                <tr>
                    <td><p>Теги:</p></td>
                    <td><input id="id_tags" name="tags" type="text" placeholder="Введите теги, разделенные пробелами" style="width: 300px;" value="{{ image.tags }}"></td>
                </tr>
                <tr>
                    <td><p>Изображение:</p></td>
                    <td>{{ form.image }} <button class="btn btn-primary" type="submit">Сохранить</button></td>
                </tr>
            </table>
		</form>
		{{ form.errors }}
	</div>
{% endblock %}